global:
  scrape_interval: 15s # Chu kỳ quét dữ liệu (mặc định 1 phút)

scrape_configs:
  - job_name: 'xdp-antiddos'
    static_configs:
      - targets: ['172.17.0.1:9101']
    scrape_interval: 1s

  - job_name: 'node_exporter'
    static_configs:
      # Sử dụng tên service trong docker-compose (node-exporter) thay vì IP
      - targets: ['node-exporter:9100']